apps/rahat/src/projects/actions/rp.action.ts, libs/sdk/src/constants/index.ts, libs/sdk/src/project/project.events.ts
- actions to get campaign log by campaign id
=> fix:rp connect actions

apps/rahat/src/projects/actions/rp.action.ts
- fix bulk disbursment create action
=> fix:fix bulk assign action

apps/beneficiary/src/beneficiary/beneficiary.service.ts
=> fix:search by phone

apps/rahat/src/projects/actions/rp.action.ts, libs/sdk/src/constants/index.ts, libs/sdk/src/project/project.events.ts
- added action to update campaign
=> Update campaign action

apps/beneficiary/src/beneficiary/beneficiary.controller.ts, apps/beneficiary/src/beneficiary/beneficiary.service.ts, apps/beneficiary/src/beneficiary/beneficiaryStat.service.ts, apps/beneficiary/src/listeners/listener.service.ts, apps/rahat/src/vendors/vendors.service.ts, libs/sdk/src/beneficiary/beneficiary.events.ts, libs/stats/src/stats.service.ts
- save reporting from projects
=> fix:reporting fixes

prisma/seed.add-elKenyadatasource.ts
- change dashboard ticket title
- added total assigned voucher
=> fix:change reporting title

apps/rahat/src/projects/actions/comms.action.ts, apps/rahat/src/projects/actions/index.ts, apps/rahat/src/projects/project.service.ts, libs/sdk/src/constants/index.ts
- Added action for communication project
=> added comms action

apps/rahat/src/projects/actions/c2c.action.ts, libs/sdk/src/constants/index.ts
- added group actions
- added connect log action
=> Added c2c groups actions

apps/rahat/src/projects/actions/c2c.action.ts, libs/sdk/src/constants/index.ts
- added groups actions in c2c project
=> fix:added groups action

apps/rahat/src/projects/actions/c2c.action.ts, libs/sdk/src/constants/index.ts, prisma/seed.add-c2c-datasource.ts
- added action for report
- added seed for c2c data source
=> fix:added c2c datasource

apps/rahat/src/grievance/grievance.service.ts, libs/extensions/src/dtos/grievance/list-grievance.dto.ts
=> grievance search

apps/rahat/src/vendors/vendors.service.ts
- added vendor data from project
- may cause issue in existing pagination
=> fix:added project data

prisma/seed.add-el-sms-voucher-args-datasource.ts
=> fix:added data source for sms voucher

apps/beneficiary/src/beneficiary/beneficiary.controller.ts, apps/beneficiary/src/beneficiary/beneficiary.service.ts, apps/beneficiary/src/listeners/listener.service.ts, libs/sdk/src/beneficiary/beneficiary.events.ts
- added listener to send disbursement created email
=> fix:added event to send disbursement email

apps/beneficiary/src/beneficiary/beneficiary.service.ts, apps/beneficiary/src/listeners/listener.service.ts, libs/sdk/src/beneficiary/beneficiary.events.ts
=> fix:added event name

apps/beneficiary/src/beneficiary/beneficiary.controller.ts, apps/beneficiary/src/beneficiary/beneficiary.service.ts
=> fix:controller typo

apps/rahat/src/utils/index.ts
=> fix:stringfy phone number

apps/rahat/src/projects/actions/ms.trigger.action.ts, bruno/auth/login.bru, bruno/environments/local.bru, bruno/rahat-triggers/List forecast data sources based on the river station.bru, bruno/rahat-triggers/List forecast data sources based on the water level.bru, bruno/rahat-triggers/activity created.bru, bruno/rahat-triggers/catergory created.bru, bruno/rahat-triggers/list activities.bru, bruno/rahat-triggers/list daily monitoring based on location.bru, bruno/rahat-triggers/list daily monitoring.bru, bruno/rahat-triggers/list project specific activities.bru, bruno/rahat-triggers/list trigger based on river basin (location).bru, bruno/rahat-triggers/phase  getAll.bru, bruno/rahat-triggers/phase  getOne.bru, bruno/rahat-triggers/phase created.bru, bruno/rahat-triggers/trigger created.bru, bruno/rahat-triggers/trigger getAll.bru
Update the `bruno` & `actions` to sync with `Rahat Triggers`
=> update command actions to sync with rahat triggers

apps/beneficiary/src/beneficiary/beneficiary.controller.ts, apps/beneficiary/src/beneficiary/beneficiary.service.ts, apps/rahat/src/beneficiary/beneficiary.controller.ts
- added projectid in getbeneficiary by phone
=> Added projectid in getbeneficiary by phone

apps/rahat/src/projects/actions/ms.trigger.action.ts, bruno/rahat-triggers/getBenef-Stake Stats data.bru, libs/sdk/src/constants/index.ts
[issue](https://github.com/rahataid/rahat-project-aa/issues/490)
=> addded a action for the communication logs  sent to benef and stakeholders

apps/rahat/src/projects/project.service.ts
- save name as unknow when name is empty
=> fix:save name unknow if beneficiary name is empty

apps/rahat/src/projects/actions/aa.action.ts, bruno/aa/payout/list payout payment providers.bru, bruno/environments/local.bru, bruno/rahat-triggers/phase  getOne.bru, libs/sdk/src/aa/aa.events.ts, libs/sdk/src/constants/index.ts
New action to get payment providers from offramp servic
=> Action to get payment providers

apps/rahat/src/projects/actions/ms.trigger.action.ts, bruno/auth/login.bru, bruno/rahat-triggers/configure threshold.bru, bruno/rahat-triggers/get vendor steallar stats.bru, bruno/rahat-triggers/list activities.bru, libs/sdk/src/constants/index.ts
https://github.com/rahataid/rahat-project-aa/issues/571
=> cmd action for the threshhold configuration

apps/beneficiary/src/beneficiary/beneficiary.controller.ts, apps/beneficiary/src/beneficiary/beneficiary.service.ts, apps/rahat/src/beneficiary/beneficiary.controller.ts, bruno/beneficiaries/export group's benef fail account.bru, libs/sdk/src/beneficiary/beneficiary.events.ts
this is an api to  export the benef data  in a group whose validation   bank account check failed
https://github.com/rahataid/rahat-platform/issues/312
=> Api for failed benef bank account after validation bank account check export

apps/rahat/src/projects/actions/ms.trigger.action.ts, libs/sdk/src/constants/index.ts
https://github.com/rahataid/rahat-project-aa/issues/631
=> Action: Fetch sources

apps/rahat/src/beneficiary/interceptor/wallet.interceptor.ts, apps/rahat/src/users/users.module.ts, apps/rahat/src/users/users.service.ts, apps/rahat/src/wallet/providers/blockchain-provider.registry.ts, apps/rahat/src/wallet/providers/evm-wallet.provider.ts, apps/rahat/src/wallet/providers/stellar-wallet.provider.ts, apps/rahat/src/wallet/wallet.service.ts, prisma/schema.prisma
- Refactored WalletInterceptor to enhance readability and maintainability.
- Updated UsersService to utilize the new wallet creation methods and handle errors more gracefully.
- Introduced BlockchainProviderRegistry to manage different wallet providers for EVM and Stellar chains.
- Added EVMWalletProvider and StellarWalletProvider to encapsulate wallet-specific logic.
- Enhanced WalletService to support dynamic wallet creation and retrieval based on chain type.
- Updated schema.prisma to include a new line for better formatting.
=> refactor: improve wallet interceptor and service for multi-chain support

.gitignore, apps/beneficiary/src/beneficiary/beneficiary.controller.ts, apps/beneficiary/src/beneficiary/beneficiary.service.ts, apps/rahat/src/beneficiary/beneficiary.controller.ts, libs/extensions/src/dtos/beneficiary/add-group-purpose.dto.ts, libs/extensions/src/dtos/beneficiary/index.ts, libs/sdk/src/beneficiary/beneficiary.events.ts, prisma/migrations/20250623104232_add_group_purpose_benf_group/migration.sql, prisma/schema.prisma
https://github.com/rahataid/rahat-project-aa/issues/640?issue=rahataid%7Crahat-project-aa%7C641
=> 641 update beneficiary group schema and create api to manage it

apps/beneficiary/src/beneficiary/beneficiary.controller.ts, apps/beneficiary/src/beneficiary/beneficiary.service.ts, apps/rahat/src/beneficiary/beneficiary.controller.ts, libs/sdk/src/beneficiary/beneficiary.events.ts
https://github.com/rahataid/rahat-project-aa/issues/617
=> Delete benef group

apps/beneficiary/src/beneficiary/beneficiary.service.ts
https://github.com/orgs/rahataid/projects/51/views/26?pane=issue&itemId=3235490076&issue=rahataid%7Crahat-platform%7C352
- Added beneficiaryGroupProject when fetching beneficiary group details
=> Added beneficiaryGroupProject

apps/beneficiary/src/processors/beneficiary.processor.ts
https://github.com/rahataid/rahat-project-aa/issues/770
=> Fix: Phn Validation Issue

apps/beneficiary/src/beneficiary/beneficiary.utils.service.ts, apps/beneficiary/src/beneficiary/beneficiaryStat.service.ts, apps/beneficiary/src/beneficiary/helpers/index.ts
This PR adds multiple functions to calculate different statistics related to beneficiaries for the core side , including:
- Mobile phone and internet access
- Digital wallet usage
- Phone type distribution
- Social Security Allowance (SSA) recipients
- Flood impact in the last 5 years
- Early warning information access
- Vulnerable population count
- Age group breakdown
- Channel usage
- SSA types
=> feat(core):stats calculation

apps/rahat/src/projects/actions/aa.action.ts, libs/sdk/src/aa/aa.events.ts, libs/sdk/src/constants/index.ts
- added inkind tracker actions
=> added inkind tracker actions
